server {
    listen 80;
    server_name patricktech.site www.patricktech.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name patricktech.site www.patricktech.site;

    ssl_certificate /etc/letsencrypt/live/patricktech.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/patricktech.site/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Explicitly handle images to prevent them from falling back to index.html
    location ~* \.(?:webp|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    error_page 404 /index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}